"""Combinatorial-topological analysis on top of CMGDB."""

from .basin_statistics import (
    OUTSIDE,
    CellIndexLookup,
    ChafeeBasinStatistics,
    PointBasinClassification,
    classify_points_in_cell_roa,
    cmgdb_morton_cell_indices,
    compute_chafee_basin_statistics,
)
from .cmgdb_features import (
    cmgdb_capabilities,
    cmgdb_provenance,
    missing_cmgdb_features,
    require_cmgdb_features,
)
from .conley_index import (
    LocalIndexComputer,
    UniformCoordinates,
    component_index_labels,
    match_nodes,
    morse_graph_cells,
    parsed_live_graph,
)
from .cmgdb_roa import (
    BOUNDARY,
    ESCAPE,
    EXACT_ROA_FILENAME,
    MULTI,
    CellROA,
    attractor_cells,
    collapse_roa_to_lca,
    compute_and_save_exact_roa,
    compute_exact_roa,
    load_exact_roa,
    save_exact_roa,
)
from .hierarchical_precomputed import HierarchicalPrecomputedBoxMap
from .morse import (
    LatentBounds,
    compute_morse_graph,
    infer_latent_bounds,
    make_box_map,
    make_box_map_numpy,
    make_box_map_uniform_precomputed,
)
from .morse_coarsening import (
    ConnectionCompleteMorseSets,
    MorseGraphQuotient,
    coarsen_morse_graph,
    compute_connection_complete_morse_sets,
    write_connection_complete_morse_sets,
    write_morse_graph_dot,
    write_quotient_morse_sets,
)
from .morse_reachability import (
    morse_singleton_reachability,
    morse_singleton_reachability_python,
)
from .morse_graph_parser import MorseGraph
from .morse_metrics import (
    check_unique_membership,
    find_morse_label_1d,
    find_seed_subdirs,
    get_minimal_labels,
)
from .tolerance import (
    Box,
    Edge,
    MorseSet,
    compute_max_semiconjugacy_error,
    compute_min_boundary_separation,
    distance_point_to_boundary,
    is_in_range,
    orthogonal_distance,
)

__all__ = [
    "BOUNDARY",
    "ESCAPE",
    "EXACT_ROA_FILENAME",
    "MULTI",
    "OUTSIDE",
    "Box",
    "CellIndexLookup",
    "CellROA",
    "ChafeeBasinStatistics",
    "ConnectionCompleteMorseSets",
    "Edge",
    "HierarchicalPrecomputedBoxMap",
    "LatentBounds",
    "LocalIndexComputer",
    "MorseGraph",
    "MorseGraphQuotient",
    "MorseSet",
    "PointBasinClassification",
    "UniformCoordinates",
    "attractor_cells",
    "check_unique_membership",
    "classify_points_in_cell_roa",
    "cmgdb_morton_cell_indices",
    "cmgdb_capabilities",
    "cmgdb_provenance",
    "missing_cmgdb_features",
    "coarsen_morse_graph",
    "collapse_roa_to_lca",
    "compute_and_save_exact_roa",
    "compute_chafee_basin_statistics",
    "compute_connection_complete_morse_sets",
    "compute_exact_roa",
    "component_index_labels",
    "compute_max_semiconjugacy_error",
    "compute_min_boundary_separation",
    "compute_morse_graph",
    "distance_point_to_boundary",
    "find_morse_label_1d",
    "find_seed_subdirs",
    "get_minimal_labels",
    "infer_latent_bounds",
    "is_in_range",
    "load_exact_roa",
    "make_box_map",
    "match_nodes",
    "morse_graph_cells",
    "make_box_map_numpy",
    "make_box_map_uniform_precomputed",
    "orthogonal_distance",
    "parsed_live_graph",
    "require_cmgdb_features",
    "save_exact_roa",
    "write_connection_complete_morse_sets",
    "write_morse_graph_dot",
    "write_quotient_morse_sets",
]
